# Generated by Django 3.2.6 on 2021-08-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acces_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fav_char',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
