# Generated by Django 3.2.5 on 2021-07-24 22:43

import character.models.chain_skill
import character.models.char_class
import character.models.character
import character.models.image
import character.models.main_attr
import character.models.sub_attr
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('name_alphabet', models.CharField(max_length=20)),
                ('icon', models.ImageField(null=True, upload_to=character.models.character.upload_path)),
                ('rarity', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'character',
                'verbose_name_plural': 'characters',
            },
        ),
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to=character.models.char_class.upload_path)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to='faction_icons')),
                ('small_gift', models.CharField(max_length=50)),
                ('big_gift', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Faction',
                'verbose_name_plural': 'Factions',
            },
        ),
        migrations.CreateModel(
            name='MainAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to=character.models.main_attr.upload_path)),
            ],
            options={
                'verbose_name': 'Mattr',
                'verbose_name_plural': 'Mattrs',
            },
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='personality_icons')),
                ('small_gift', models.CharField(max_length=50)),
                ('big_gift', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Personality',
                'verbose_name_plural': 'Personalities',
            },
        ),
        migrations.CreateModel(
            name='SubAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to=character.models.sub_attr.upload_path)),
            ],
            options={
                'verbose_name': 'Sattr',
                'verbose_name_plural': 'Sattrs',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('hit_point', models.IntegerField()),
                ('state_id', models.OneToOneField(db_column='state', on_delete=django.db.models.deletion.CASCADE, related_name='state', to='character.character')),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'states',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ascension_0', models.ImageField(upload_to=character.models.image.upload_path)),
                ('ascension_3', models.ImageField(upload_to=character.models.image.upload_path)),
                ('image_id', models.OneToOneField(db_column='image', on_delete=django.db.models.deletion.CASCADE, to='character.character', verbose_name='image')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='char_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.charclass', verbose_name='클래스'),
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.faction', verbose_name='소속 세력'),
        ),
        migrations.AddField(
            model_name='character',
            name='main_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.mainattribute', verbose_name='주속성'),
        ),
        migrations.AddField(
            model_name='character',
            name='personality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.personality', verbose_name='성격'),
        ),
        migrations.AddField(
            model_name='character',
            name='sub_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.subattribute', verbose_name='부속성'),
        ),
        migrations.CreateModel(
            name='ChainSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to=character.models.chain_skill.upload_path)),
                ('lv1_tiles', models.CharField(max_length=10)),
                ('lv1_text', models.CharField(max_length=300)),
                ('lv2_tiles', models.CharField(max_length=10)),
                ('lv2_text', models.CharField(max_length=300)),
                ('lv3_tiles', models.CharField(max_length=10)),
                ('lv3_text', models.CharField(max_length=300)),
                ('skill_id', models.OneToOneField(db_column='chain_skill', on_delete=django.db.models.deletion.CASCADE, to='character.character', verbose_name='chain skill')),
            ],
            options={
                'verbose_name': 'chain skill',
                'verbose_name_plural': 'chain skills',
            },
        ),
    ]
