# Generated by Django 3.2.5 on 2021-07-29 12:21

import character.models.active_skill
import character.models.chain_skill
import character.models.char_class
import character.models.character
import character.models.equip_skill
import character.models.equipment
import character.models.image
import character.models.main_attr
import character.models.sub_attr
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_alphabet', models.CharField(max_length=30)),
                ('icon', models.ImageField(blank=True, upload_to=character.models.character.upload_path)),
                ('logo', models.ImageField(blank=True, upload_to=character.models.character.upload_path)),
                ('rarity', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'verbose_name': 'character',
                'verbose_name_plural': 'characters',
            },
        ),
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=character.models.char_class.upload_path)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('icon', models.ImageField(blank=True, upload_to='faction_icons')),
                ('small_gift', models.CharField(blank=True, max_length=100)),
                ('big_gift', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Faction',
                'verbose_name_plural': 'Factions',
            },
        ),
        migrations.CreateModel(
            name='MainAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('icon', models.ImageField(blank=True, upload_to=character.models.main_attr.upload_path)),
            ],
            options={
                'verbose_name': 'Mattr',
                'verbose_name_plural': 'Mattrs',
            },
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('small_gift', models.CharField(blank=True, max_length=100)),
                ('big_gift', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Personality',
                'verbose_name_plural': 'Personalities',
            },
        ),
        migrations.CreateModel(
            name='SubAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('icon', models.ImageField(blank=True, upload_to=character.models.sub_attr.upload_path)),
            ],
            options={
                'verbose_name': 'Sattr',
                'verbose_name_plural': 'Sattrs',
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('voice_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='character.character')),
            ],
            options={
                'verbose_name': 'voice',
                'verbose_name_plural': 'voices',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.CharField(blank=True, max_length=6)),
                ('defence', models.CharField(blank=True, max_length=6)),
                ('hit_point', models.CharField(blank=True, max_length=6)),
                ('state_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='character.character')),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'states',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ascension_0', models.ImageField(blank=True, upload_to=character.models.image.upload_path)),
                ('ascension_3', models.ImageField(blank=True, upload_to=character.models.image.upload_path)),
                ('image_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='character.character')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='EquipSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('icon', models.ImageField(blank=True, upload_to=character.models.equip_skill.upload_path)),
                ('lv1_text', models.TextField(blank=True)),
                ('lv3_text', models.TextField(blank=True)),
                ('lv6_text', models.TextField(blank=True)),
                ('lv10_text', models.TextField(blank=True)),
                ('asc2_enhance', models.BooleanField(default=False)),
                ('asc2_lv1_text', models.TextField(blank=True)),
                ('asc2_lv3_text', models.TextField(blank=True)),
                ('asc2_lv6_text', models.TextField(blank=True)),
                ('asc2_lv10_text', models.TextField(blank=True)),
                ('asc3_enhance', models.BooleanField(default=False)),
                ('asc3_lv1_text', models.TextField(blank=True)),
                ('asc3_lv3_text', models.TextField(blank=True)),
                ('asc3_lv6_text', models.TextField(blank=True)),
                ('asc3_lv10_text', models.TextField(blank=True)),
                ('skill_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equip_skill', to='character.character')),
            ],
            options={
                'verbose_name': 'equip skill input name, icon, texts, enhanced skill',
                'verbose_name_plural': 'equip skills',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=character.models.equipment.upload_path)),
                ('text', models.TextField(blank=True)),
                ('lv1_text', models.TextField(blank=True)),
                ('lv3_text', models.TextField(blank=True)),
                ('lv6_text', models.TextField(blank=True)),
                ('lv10_text', models.TextField(blank=True)),
                ('lv1_state_text', models.TextField(blank=True)),
                ('lv2_state_text', models.TextField(blank=True)),
                ('lv4_state_text', models.TextField(blank=True)),
                ('lv5_state_text', models.TextField(blank=True)),
                ('lv7_state_text', models.TextField(blank=True)),
                ('lv8_state_text', models.TextField(blank=True)),
                ('lv9_state_text', models.TextField(blank=True)),
                ('equip_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='character.character')),
            ],
            options={
                'verbose_name': 'equipment input only name, image, text',
                'verbose_name_plural': 'equipments',
            },
        ),
        migrations.CreateModel(
            name='CharFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('birthday', models.CharField(blank=True, max_length=20)),
                ('birthplace', models.CharField(blank=True, max_length=50)),
                ('element', models.CharField(blank=True, max_length=20)),
                ('affilition', models.CharField(blank=True, max_length=100)),
                ('fighting_style', models.CharField(blank=True, max_length=200)),
                ('file_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='char_file', to='character.character')),
            ],
            options={
                'verbose_name': 'file autoinput: name, gender(여),elemnet, affil,ftile(equip)',
                'verbose_name_plural': 'char files',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='char_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.charclass', verbose_name='클래스'),
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.faction', verbose_name='소속 세력'),
        ),
        migrations.AddField(
            model_name='character',
            name='main_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.mainattribute', verbose_name='주속성'),
        ),
        migrations.AddField(
            model_name='character',
            name='personality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.personality', verbose_name='성격'),
        ),
        migrations.AddField(
            model_name='character',
            name='sub_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.subattribute', verbose_name='부속성'),
        ),
        migrations.CreateModel(
            name='ChainSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('icon', models.ImageField(blank=True, upload_to=character.models.chain_skill.upload_path)),
                ('lv1_tiles', models.PositiveSmallIntegerField(blank=True)),
                ('lv1_text', models.TextField(blank=True)),
                ('lv2_tiles', models.PositiveSmallIntegerField(blank=True)),
                ('lv2_text', models.TextField(blank=True)),
                ('lv3_tiles', models.PositiveSmallIntegerField(blank=True)),
                ('lv3_text', models.TextField(blank=True)),
                ('skill_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chain_skill', to='character.character')),
            ],
            options={
                'verbose_name': 'chain skill',
                'verbose_name_plural': 'chain skills',
            },
        ),
        migrations.CreateModel(
            name='Breakthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_1', models.TextField(blank=True)),
                ('count_2', models.TextField(blank=True)),
                ('count_3', models.TextField(blank=True)),
                ('count_4', models.TextField(blank=True)),
                ('count_5', models.TextField(blank=True)),
                ('count_6', models.TextField(blank=True)),
                ('brth_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakthrough', to='character.character')),
            ],
            options={
                'verbose_name': 'breakthrough autoinput = 6성 기본 텍스트',
                'verbose_name_plural': 'breakthroughs',
            },
        ),
        migrations.CreateModel(
            name='Ascension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv1', models.TextField(blank=True, null=True)),
                ('lv2', models.TextField(blank=True, null=True)),
                ('lv3', models.TextField(blank=True, null=True)),
                ('asc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ascension', to='character.character')),
            ],
            options={
                'verbose_name': 'ascension autoinput = lv1: equip_lv1 text',
                'verbose_name_plural': 'ascensions',
            },
        ),
        migrations.CreateModel(
            name='ActiveSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('cooltime', models.CharField(blank=True, max_length=6)),
                ('preemptive', models.CharField(blank=True, max_length=4)),
                ('icon', models.ImageField(blank=True, upload_to=character.models.active_skill.upload_path)),
                ('text', models.TextField(blank=True)),
                ('brth_skill_1_br', models.PositiveSmallIntegerField(default=7)),
                ('brth_skill_2_br', models.PositiveSmallIntegerField(default=7)),
                ('asc2_change', models.BooleanField(default=False)),
                ('asc3_change', models.BooleanField(default=False)),
                ('asc0_brth_skill_1_cooltime', models.CharField(blank=True, max_length=6)),
                ('asc0_brth_skill_1_preemptive', models.CharField(blank=True, max_length=4)),
                ('asc0_brth_skill_1_text', models.TextField(blank=True)),
                ('asc0_brth_skill_2_cooltime', models.CharField(blank=True, max_length=6)),
                ('asc0_brth_skill_2_preemptive', models.CharField(blank=True, max_length=4)),
                ('asc0_brth_skill_2_text', models.TextField(blank=True)),
                ('asc2_brth_skill_0_cooltime', models.CharField(blank=True, max_length=6)),
                ('asc2_brth_skill_0_preemptive', models.CharField(blank=True, max_length=4)),
                ('asc2_brth_skill_0_text', models.TextField(blank=True)),
                ('asc2_brth_skill_1_cooltime', models.CharField(blank=True, max_length=6)),
                ('asc2_brth_skill_1_preemptive', models.CharField(blank=True, max_length=4)),
                ('asc2_brth_skill_1_text', models.TextField(blank=True)),
                ('asc2_brth_skill_2_cooltime', models.CharField(blank=True, max_length=6)),
                ('asc2_brth_skill_2_preemptive', models.CharField(blank=True, max_length=4)),
                ('asc2_brth_skill_2_text', models.TextField(blank=True)),
                ('asc3_brth_skill_0_cooltime', models.CharField(blank=True, max_length=6)),
                ('asc3_brth_skill_0_preemptive', models.CharField(blank=True, max_length=4)),
                ('asc3_brth_skill_0_text', models.TextField(blank=True)),
                ('asc3_brth_skill_1_cooltime', models.CharField(blank=True, max_length=6)),
                ('asc3_brth_skill_1_preemptive', models.CharField(blank=True, max_length=4)),
                ('asc3_brth_skill_1_text', models.TextField(blank=True)),
                ('asc3_brth_skill_2_cooltime', models.CharField(blank=True, max_length=6)),
                ('asc3_brth_skill_2_preemptive', models.CharField(blank=True, max_length=4)),
                ('asc3_brth_skill_2_text', models.TextField(blank=True)),
                ('skill_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_skill', to='character.character')),
            ],
            options={
                'verbose_name': 'active skill chanefalse = 하위스킬입력, brth_br=7:강화없음',
                'verbose_name_plural': 'active skills',
            },
        ),
    ]
