# Generated by Django 3.2.5 on 2021-07-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeskill',
            name='asc0_brth_skill_1_preemptive',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc0_brth_skill_2_preemptive',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc2_brth_skill_0_preemptive',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc2_brth_skill_1_preemptive',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc2_brth_skill_2_preemptive',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc3_brth_skill_0_preemptive',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc3_brth_skill_1_preemptive',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc3_brth_skill_2_preemptive',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
