# Generated by Django 3.2.5 on 2021-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainskill',
            name='lv1_tiles',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='lv2_tiles',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='lv3_tiles',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
