# Generated by Django 3.2.5 on 2021-07-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainskill',
            name='lv1_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='lv1_tiles',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='lv2_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='lv2_tiles',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='lv3_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='lv3_tiles',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='name_alphabet',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='rarity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='charclass',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='faction',
            name='big_gift',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faction',
            name='small_gift',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mainattribute',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personality',
            name='big_gift',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personality',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personality',
            name='small_gift',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subattribute',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
