# Generated by Django 3.2.5 on 2021-07-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20210725_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.charclass', verbose_name='클래스'),
        ),
        migrations.AlterField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.faction', verbose_name='소속 세력'),
        ),
        migrations.AlterField(
            model_name='character',
            name='main_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.mainattribute', verbose_name='주속성'),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.personality', verbose_name='성격'),
        ),
        migrations.AlterField(
            model_name='character',
            name='sub_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.subattribute', verbose_name='부속성'),
        ),
    ]
