# Generated by Django 3.2.5 on 2021-07-25 11:14

import character.models.active_skill
import character.models.chain_skill
import character.models.equip_skill
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20210725_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeskill',
            name='asc0_brth_skill_1_cooltime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc0_brth_skill_1_preemptive',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc0_brth_skill_1_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc0_brth_skill_2_cooltime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc0_brth_skill_2_preemptive',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc0_brth_skill_2_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc2_brth_skill_0_cooltime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc2_brth_skill_0_preemptive',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc2_brth_skill_0_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc2_brth_skill_1_cooltime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc2_brth_skill_1_preemptive',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc2_brth_skill_1_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc2_brth_skill_2_cooltime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc2_brth_skill_2_preemptive',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc2_brth_skill_2_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc3_brth_skill_0_cooltime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc3_brth_skill_0_preemptive',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc3_brth_skill_0_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc3_brth_skill_1_cooltime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc3_brth_skill_1_preemptive',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc3_brth_skill_1_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc3_brth_skill_2_cooltime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc3_brth_skill_2_preemptive',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='asc3_brth_skill_2_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='cooltime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=character.models.active_skill.upload_path),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='preemptive',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=character.models.chain_skill.upload_path),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='lv1_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='lv1_tiles',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='lv2_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='lv2_tiles',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='lv3_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='lv3_tiles',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chainskill',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='asc2_lv10_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='asc2_lv1_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='asc2_lv3_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='asc2_lv6_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='asc3_lv10_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='asc3_lv1_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='asc3_lv3_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='asc3_lv6_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=character.models.equip_skill.upload_path),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='lv10_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='lv1_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='lv3_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='lv6_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipskill',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
