# Generated by Django 3.2.5 on 2021-07-25 15:29

import character.models.equipment
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20210725_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=character.models.equipment.upload_path)),
                ('text', models.TextField(blank=True, null=True)),
                ('lv1_text', models.TextField(blank=True, null=True)),
                ('lv3_text', models.TextField(blank=True, null=True)),
                ('lv6_text', models.TextField(blank=True, null=True)),
                ('lv10_text', models.TextField(blank=True, null=True)),
                ('lv1_state_text', models.CharField(blank=True, max_length=200, null=True)),
                ('lv2_state_text', models.CharField(blank=True, max_length=200, null=True)),
                ('lv4_state_text', models.CharField(blank=True, max_length=200, null=True)),
                ('lv5_state_text', models.CharField(blank=True, max_length=200, null=True)),
                ('lv7_state_text', models.CharField(blank=True, max_length=200, null=True)),
                ('lv8_state_text', models.CharField(blank=True, max_length=200, null=True)),
                ('lv9_state_text', models.CharField(blank=True, max_length=200, null=True)),
                ('equip_id', models.OneToOneField(db_column='equipme', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='character.character')),
            ],
            options={
                'verbose_name': 'equipment',
                'verbose_name_plural': 'equipments',
            },
        ),
    ]
