# Generated by Django 3.2.5 on 2021-07-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20210726_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voice_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='character.character')),
            ],
            options={
                'verbose_name': 'voice',
                'verbose_name_plural': 'voices',
            },
        ),
        migrations.CreateModel(
            name='CharFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('birthday', models.CharField(max_length=20)),
                ('birthplace', models.CharField(max_length=50)),
                ('element', models.CharField(max_length=20)),
                ('affilition', models.CharField(max_length=100)),
                ('fighting_style', models.CharField(max_length=200)),
                ('file_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='char_file', to='character.character')),
            ],
            options={
                'verbose_name': 'char file',
                'verbose_name_plural': 'char files',
            },
        ),
        migrations.CreateModel(
            name='Breakthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_1', models.TextField(blank=True, null=True)),
                ('count_2', models.TextField(blank=True, null=True)),
                ('count_3', models.TextField(blank=True, null=True)),
                ('count_4', models.TextField(blank=True, null=True)),
                ('count_5', models.TextField(blank=True, null=True)),
                ('count_6', models.TextField(blank=True, null=True)),
                ('brth_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakthrough', to='character.character')),
            ],
            options={
                'verbose_name': 'breakthrough',
                'verbose_name_plural': 'breakthroughs',
            },
        ),
        migrations.CreateModel(
            name='Ascension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv1', models.TextField()),
                ('lv2', models.TextField()),
                ('lv3', models.TextField()),
                ('asc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ascension', to='character.character')),
            ],
            options={
                'verbose_name': 'ascension',
                'verbose_name_plural': 'ascensions',
            },
        ),
    ]
