# Generated by Django 3.2.5 on 2021-07-25 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_ascension_breakthrough_charfile_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='voice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='character.character'),
        ),
    ]
