# Generated by Django 3.2.5 on 2021-07-25 16:05

import character.models.char_class
import character.models.image
import character.models.main_attr
import character.models.sub_attr
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_alter_voice_voice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personality',
            name='icon',
        ),
        migrations.AlterField(
            model_name='ascension',
            name='lv1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ascension',
            name='lv2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ascension',
            name='lv3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='rarity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charclass',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=character.models.char_class.upload_path),
        ),
        migrations.AlterField(
            model_name='charclass',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='charfile',
            name='affilition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charfile',
            name='birthday',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='charfile',
            name='birthplace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='charfile',
            name='element',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='charfile',
            name='fighting_style',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='charfile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='charfile',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='charfile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='charfile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='big_gift',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='faction_icons'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='small_gift',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='ascension_0',
            field=models.ImageField(blank=True, null=True, upload_to=character.models.image.upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='ascension_3',
            field=models.ImageField(blank=True, null=True, upload_to=character.models.image.upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='character.character'),
        ),
        migrations.AlterField(
            model_name='mainattribute',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=character.models.main_attr.upload_path),
        ),
        migrations.AlterField(
            model_name='mainattribute',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personality',
            name='big_gift',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personality',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personality',
            name='small_gift',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subattribute',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=character.models.sub_attr.upload_path),
        ),
        migrations.AlterField(
            model_name='subattribute',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='character.character'),
        ),
    ]
