# Generated by Django 3.2.5 on 2021-07-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_auto_20210726_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeskill',
            name='asc2_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activeskill',
            name='asc3_change',
            field=models.BooleanField(default=False),
        ),
    ]
