# Generated by Django 3.2.5 on 2021-07-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_auto_20210726_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascension',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
