# Generated by Django 3.2.5 on 2021-07-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0012_ascension_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ascension',
            name='name',
        ),
    ]
