# Generated by Django 3.2.5 on 2021-07-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0013_remove_ascension_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='lv1_state_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='lv2_state_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='lv4_state_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='lv5_state_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='lv7_state_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='lv8_state_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='lv9_state_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
