# Generated by Django 3.2.5 on 2021-07-26 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0014_auto_20210726_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='skill_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='character.equipskill'),
            preserve_default=False,
        ),
    ]
