# Generated by Django 3.2.5 on 2021-07-26 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0015_equipment_skill_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='skill_id',
        ),
    ]
