# Generated by Django 3.2.5 on 2021-07-26 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0016_remove_equipment_skill_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ascension',
            options={'verbose_name': 'ascension input lv2, lv3', 'verbose_name_plural': 'ascensions'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'equipment input only name, image, text', 'verbose_name_plural': 'equipments'},
        ),
        migrations.AlterModelOptions(
            name='equipskill',
            options={'verbose_name': 'equip skill input only name, icon, enhanced skill', 'verbose_name_plural': 'equip skills'},
        ),
    ]
