# Generated by Django 3.2.5 on 2021-07-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0017_auto_20210726_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeskill',
            options={'verbose_name': 'active skill chanefalse = 하위스킬입력, brth_br=7:강화없음', 'verbose_name_plural': 'active skills'},
        ),
        migrations.AlterModelOptions(
            name='ascension',
            options={'verbose_name': 'ascension autoinput = lv1: equip_lv1 text', 'verbose_name_plural': 'ascensions'},
        ),
        migrations.AlterModelOptions(
            name='breakthrough',
            options={'verbose_name': 'breakthrough autoinput = 6성 기본 텍스트', 'verbose_name_plural': 'breakthroughs'},
        ),
        migrations.AlterModelOptions(
            name='charfile',
            options={'verbose_name': 'file autoinput: name, gender(여),elemnet, affil,ftile(equip)', 'verbose_name_plural': 'char files'},
        ),
        migrations.AlterModelOptions(
            name='equipskill',
            options={'verbose_name': 'equip skill input name, icon, texts, enhanced skill', 'verbose_name_plural': 'equip skills'},
        ),
    ]
